taga3s/Rhythmate-Service

src/model/funcs/dateTime.ts
src/model/funcs/exp.ts
src/model/quest/cron_quest_model.ts
src/model/quest/quest_model.ts
src/model/quest/types.ts
src/model/user/user_model.ts
src/model/weeklyReport/cron_weekly_report.model.ts
src/model/weeklyReport/weekly_report_model.ts
src/service/quest/finish_quest_service.ts

[Service] リファクタリング

---

src/model/weeklyReport/weekly_report_model.ts
src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts

多目的になってた関数を分割し、見直しました。
クエストを作って完了まで待ってください。そのあと統計ページに反映されてるか確認してください

refac:多目的クラスの見直し

---

src/controller/user/user_controller.ts

本番反映 2024-03-13-15-43

---

src/service/quest/force_finish_quest_service.ts

本番反映 2024-03-13-16-31

---

src/controller/user/user_controller.ts
src/model/quest/cron_quest_model.ts
src/model/weeklyReport/cron_weekly_report.model.ts
src/pkg/logger.ts

- #33 
- Loggerは今の状態でも`error`, `info`, `warn`が出るのでこれで良いかなと思いました。
- その他軽いリファクタリングです。
- `logger.error()`で値が出れば、特に大丈夫です。

[Service] ロガーの修正、不要なコード削除など

---

src/controller/tag/response.ts
src/controller/tag/tag_controller.ts
src/model/tag/tag_model.ts
src/route/tag.ts
src/service/tag/list_tags_service.ts

- close #37 
- Tag周りの命名修正やリファクタリングをしました。
- postmanを用いてテストしてみてください。
1. サインアップ・ログインをする。
```
// POST: http://localhost:3000/v1/users/signup
{
name: "54kg";
email: "54kg@gmail.com";
password: "p@ssword";
password_confirmation: "p@ssword";
}
// POST: http://localhost:3000/v1/login
{
email:  "54kg@gmail.com;
password: "p@ssword";
}
得られたクッキーをコピペしておく
```
2. タグの各種APIを叩く。`src/controller/tag/request.ts`にリクエストの型はあります。また各種エンドポイントは`src/route/tag.ts`の中にあります。頑張って読み解いてみて、APIを叩いてみてください！また、先ほどのクッキーをリクエストのヘッダーに追加しておく必要があります。
わからなかったらもちろん聞いてください。

[Service] Tagの命名修正等

---

src/db/types.ts
src/model/quest/cron_quest_model.ts
src/model/quest/quest_model.ts
src/model/tag/tag_model.ts
src/model/user/user_model.ts
src/model/weeklyReport/cron_weekly_report.model.ts
src/model/weeklyReport/weekly_report_model.ts
src/service/quest/create_quest_service.ts
src/service/quest/delete_quest_service.ts
src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts
src/service/quest/start_quest_service.ts
src/service/quest/update_quest_service.ts
src/service/tag/create_tag_service.ts
src/service/tag/delete_tag_service.ts
src/service/tag/update_tag_service.ts
src/service/user/signup_service.ts
src/service/user/update_login_user_service.ts
src/service/weeklyReport/create_weekly_report_service.ts
src/service/weeklyReport/delete_weekly_report_service.ts
src/service/weeklyReport/update_weekly_report_service.ts

タグと週報をトランザクション化

---

src/model/quest/quest_model.ts
src/model/tag/tag_model.ts
src/service/tag/update_tag_service.ts

fix: timezoneはutcをデフォルトに

---

src/cron-job/quest.ts
src/model/weeklyReport/weekly_report_model.ts

fix: cron jobの日時一時的に変更

---

src/controller/quest/quest_controller.ts
src/controller/quest/request.ts
src/cron-job/quest.ts
src/service/quest/create_quest_service.ts

[Service] クーロンジョブの時間修正とクエスト作成ロジックの修正

---

src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts

- クエスト強制終了時のロジック修正
- マジックナンバーを避けるように

[Service] クエスト強制終了時のロジックを修正

---

docs/db/mermaid.md

DB設計の見直をしER図を更新しました
- badges, badges_listのテーブルを作成
- questsの使用していないカラムの削除

DB設計の見直しとER図を更新

---

src/controller/quest/quest_controller.ts
src/controller/quest/response.ts
src/service/quest/create_quest_service.ts
src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts
src/service/quest/start_quest_service.ts
src/service/quest/update_quest_service.ts

- issue #70 
- クエストのレスポンスの型を修正しました。
- フロントを立ち上げてもらって、クエストが作成された瞬間、継続レベルが正しく反映されていることを確認してください。
- いつも通り、立ち上げればと思います。

[Service] クエストのレスポンスの型を修正

---

prisma/migrations/20240403094909_/migration.sql
prisma/schema.prisma
src/controller/weeklyReport/response.ts
src/controller/weeklyReport/weekly_report_controller.ts
src/cron-job/weeklyReport.ts
src/model/weeklyReport/types.ts
src/model/weeklyReport/weekly_report_model.ts
src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts
src/service/user/auth_service.ts
src/service/weeklyReport/create_weekly_report_service.ts
src/service/weeklyReport/update_weekly_report_service.ts

[Service] 失敗数をチャートに追加 

---

src/model/tag/tag_model.ts
src/service/tag/update_tag_service.ts

fix: update modelにcolorを追加

---

src/cron-job/weeklyReport.ts

本番反映 2024-04-07 23:02:00

---

prisma/migrations/20240407152924_/migration.sql
prisma/schema.prisma
src/service/tag/update_tag_service.ts

[Service] カスケード制約をつける

---

prisma/migrations/20240407152924_/migration.sql
prisma/schema.prisma
src/cron-job/weeklyReport.ts
src/service/tag/update_tag_service.ts

本番反映 2024-04-08 21:10:00

---

package-lock.json
package.json
src/app.ts

[Service] プラクティスに則り、helmetを利用

---

prisma/schema.prisma

model User {
id              String   @id @default(uuid())
name            String
email           String
profileImageUrl String
exp             Int      @default(0)
level           Int      @default(1)
createdAt       DateTime @default(now())
updatedAt       DateTime @updatedAt
quests          Quest[]
tags            Tag[]
weeklyReports   WeeklyReport[]
Badges          Badge[]
}
のprofileImageUrl String?を取り除きました

fix:prisma model Userの修正

---

src/model/user/user_model.ts

本番反映 2024-04-10 09:28:40

---

src/controller/user/response.ts
src/controller/user/user_controller.ts
src/model/user/types.ts
src/model/user/user_model.ts
src/service/user/auth_service.ts
src/service/user/get_login_user_service.ts
src/service/user/update_login_user_service.ts

feat:アカウント画像の取得

---

src/controller/user/response.ts
src/controller/user/user_controller.ts
src/model/user/types.ts
src/model/user/user_model.ts
src/service/user/auth_service.ts
src/service/user/get_login_user_service.ts
src/service/user/update_login_user_service.ts

本番反映 2024-04-10 22:43:20

---

src/service/user/auth_service.ts

本番反映 2024-04-10 22:56:00

---

src/service/user/auth_service.ts

本番反映 2024-04-10 23:04:45

---

src/controller/user/response.ts
src/controller/user/user_controller.ts
src/model/user/user_model.ts
src/route/user.ts
src/service/user/delete_user_service.ts

ユーザー削除APIを実装しました。フロントと合わせてご確認ください

[Service] Implemet of user deletion API

---

src/cron-job/weeklyReport.ts

fix: cron jobの日時の修正

---

.env.example
src/app.ts
src/controller/user/request.ts
src/controller/user/response.ts
src/controller/user/user_controller.ts
src/firebase/config.ts
src/model/user/user_model.ts
src/service/user/update_login_user_service.ts

- #112 
- 画像アップロード機能の仕組みづくりをしました。Firebase Storageを利用しています。
- フロントのPRがマージされてから。

[Service] 画像アップロード機能の仕組みづくり

---

.github/workflows/test-submodule.yaml

[Service] submodule更新のためのワークフローのテスト

---

src/controller/user/user_controller.ts

cookieのexpiresを設定

---

.github/workflows/ci.yaml
.github/workflows/deploy-swagger.yaml

chore: update workflow

---

.github/workflows/ci.yaml
.github/workflows/dispatch.yaml
README.md

- none
- workflowsの修正です。
- READMEの更新も行いました。

fix workflows

---

compose.yaml
docs/api/openapi.yaml
src/pkg/schema.gen.ts

fix openapi docs and docker compose

---

docs/api/openapi.yaml
src/controller/badge/badge_controller.ts
src/controller/quest/quest_controller.ts
src/controller/tag/tag_controller.ts
src/controller/user/user_controller.ts
src/controller/weeklyReport/weekly_report_controller.ts
src/pkg/schema.gen.ts
src/route/middlewares/auth.ts
src/service/user/auth_service.ts

fix auth token

---

docs/api/openapi.yaml
src/controller/badge/badge_controller.ts
src/controller/quest/quest_controller.ts
src/controller/tag/tag_controller.ts
src/controller/user/user_controller.ts
src/controller/weeklyReport/weekly_report_controller.ts
src/pkg/schema.gen.ts
src/route/middlewares/auth.ts
src/service/user/auth_service.ts

Reverts taga3s/Rhythmate-Service#141

Revert "【本番反映】2024-10-04 22:43:03"

---

src/model/quest/quest_model.ts
src/service/quest/delete_quest_service.ts
src/service/quest/finish_quest_service.ts
src/service/quest/force_finish_quest_service.ts
src/service/quest/start_quest_service.ts
src/service/quest/update_quest_service.ts

refactor: quest_model args

---

package.json
pnpm-lock.yaml

update some libs to the latest
